# Generated by Django 3.0.6 on 2020-06-01 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mugauth', '0002_remove_account_search_algorythm'),
        ('foodfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAlgorythm',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('algorythm', models.CharField(choices=[('ByFat', 'By Fat'), ('BySalt', 'By Salt'), ('ByNutriments', 'By Nutriments'), ('ByCategory', 'By Category')], default='ByFat', max_length=63)),
            ],
        ),
    ]
