# Generated by Django 3.0.7 on 2020-06-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder', '0002_searchalgorythm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('nutriments', models.CharField(max_length=2048)),
                ('img_front', models.ImageField(upload_to='food/front/')),
                ('img_back', models.ImageField(upload_to='food/back/')),
                ('nutriscore', models.CharField(max_length=7)),
                ('update_date', models.DateField(auto_now=True)),
                ('category_set', models.ManyToManyField(to='foodfinder.Category')),
            ],
        ),
    ]
