# Generated by Django 3.0.8 on 2020-07-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder', '0016_auto_20200708_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodhistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
