# Generated by Django 3.0.7 on 2020-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder', '0003_category_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='img_back',
        ),
        migrations.RemoveField(
            model_name='food',
            name='img_front',
        ),
        migrations.AddField(
            model_name='food',
            name='img_back_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='img_front_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='nutriscore',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default=None, max_length=7, null=True),
        ),
    ]
