# Generated by Django 3.0.7 on 2020-06-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder', '0009_auto_20200614_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='nutriment_set',
        ),
    ]
