# Generated by Django 3.0.7 on 2020-06-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder', '0010_remove_food_nutriment_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodnutriment',
            name='nutriment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_nutriment_set', to='foodfinder.Nutriment'),
        ),
    ]
