# Generated by Django 3.0.7 on 2020-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfinder', '0014_auto_20200623_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchalgorythm',
            name='algorythm',
            field=models.CharField(choices=[('ByCategory', 'By Category')], default='ByCategory', max_length=63),
        ),
    ]
