# Generated by Django 3.0.6 on 2020-06-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='search_algorythm',
        ),
    ]
